### ISSUE TITLE
Use webgl2 `draw_instanced_base_vertex_base_instance` extensions if available

### ISSUE THREAD

**Issue by micahscopes** [andykswong/mugl#21]
These webgl2 draft extensions let you start instanced drawing from an arbitrary base instance, very much like `firstInstance` in WebGPU:
- https://www.khronos.org/registry/webgl/extensions/WEBGL_draw_instanced_base_vertex_base_instance/
- https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/

It'd be nice to use them if they're available

**Comment by andykswong** [comment]
Cleaning up issues. While the extension nicely provides the firstInstance/firstVertex functionalities, it is still a draft and not widely supported by browsers as of now. Will revisit when the extensions become approved / more widely adopted.
