### ISSUE TITLE
Webgpu support?

### ISSUE THREAD

**Issue by kefniark** [andykswong/mugl#30]
## Description
Chrome webgpu support is [around the corner](https://developer.chrome.com/blog/webgpu-release/), should be finally enable by default in chrome 113 in like ~3 weeks.

Is mugl will remains purely webgl2, or is there any plan to also handle webgpu (maybe providing some webgl2 fallback).
The syntax is really similar and having the combo webgpu + assemblyscript binding sounds really promising.

**Comment by andykswong** [comment]
Yes! It's always the goal to transition to WebGPU when I created mugl.
Experimental WebGPU support was just added in v0.3.0. Switching between WebGPU and WebGL backend at runtime is possible: https://andykswong.github.io/mugl/examples

**Comment by kefniark** [comment]
Wow really cool, thanks for that.
I was experimenting with some Zig Raylib or Zig GLFW -> wasm for the past few days.
But suddenly with this solution, assemblyscript looks interesting once again 😄

P.S. on your website, the API Documentation looks broken (404 not found: https://andykswong.github.io/mugl/docs)
